[build]
publish = "public"
command = "npm install && node ./esmscript.prod.mjs && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
